PORTNAME=	hyperpolyglot
DISTVERSIONPREFIX=	v
DISTVERSION=	20240731_1
CATEGORIES=	sysutils

MAINTAINER=	freebsd@superscript.com
COMMENT=	Programming language detection
WWW=		https://github.com/monkslc/hyperpolyglot

USE_GITHUB=     yes
GH_ACCOUNT=     monkslc
GH_TAGNAME=     a55a3b5

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE-MIT

USES=		cargo pkgconfig

.include <bsd.port.mk>
