PORTNAME=	ccase
DISTVERSIONPREFIX=	v
DISTVERSION=	0.4.1
CATEGORIES=	textproc

MAINTAINER=	freebsd@superscript.com
COMMENT=	Convert strings between different case conventions
WWW=		https://github.com/rutrum/ccase

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE.md

USES=		cargo
USE_GITHUB=	yes
GH_ACCOUNT=	rutrum

PLIST_FILES=	bin/ccase

.include <bsd.port.mk>

