PORTNAME=	tree-sitter-python
DISTVERSIONPREFIX=	v
DISTVERSION=	0.23.2
CATEGORIES=	devel

MAINTAINER=	freebsd@superscript.com
COMMENT=	Python grammar for tree-sitter
WWW=		https://tree-sitter.github.io/

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		gmake
USE_GITHUB=	yes
GH_ACCOUNT=	tree-sitter


# post-install:
# 	${STRIP_CMD} ${STAGEDIR}${PREFIX}/lib/libtree-sitter.so.*

.include <bsd.port.mk>
